# Generated by Django 4.2 on 2023-10-20 12:45
from datetime import datetime, timezone

from django.db import migrations


def add_sample_data(apps, schema_editor):
    pub_date = datetime.now(timezone.utc)
    TenantModel = apps.get_model('polls.Tenant')
    QuestionModel = apps.get_model('polls.Question')
    ChoiceModel = apps.get_model('polls.Choice')
    tenant1 = TenantModel.objects.create(name='Tenant 1', host='tenant1.com')
    tenant2 = TenantModel.objects.create(name='Tenant 2', host='tenant2.com')
    for tenant in (tenant1, tenant2):
        for i in range(2):
            question = QuestionModel.objects.create(
                tenant=tenant,
                question_text=f'A {i + 1} question from {tenant.name}',
                pub_date=pub_date,
            )
            for j in range(3):
                ChoiceModel.objects.create(
                    tenant=tenant,
                    question=question,
                    choice_text=f'A {j + 1} choice for {i + 1} question from {tenant.name}',
                    votes=j+1,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data, lambda *args: None),
    ]
